version: '3'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile  # Replace with your actual Dockerfile name
    ports:
      - "8082:80"
    networks:
      - allNet

  nginx-reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    networks:
      - allNet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  allNet:
