version: '3'

services:
  angular-app:
    image: node18-img
    ports:
      - "8082:80"
    networks:
      - allNet

  backend-api:
    image: appnodebackend
    ports:
      - "3000:3000"
    networks:
      - allNet

  nginx-reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    networks:
      - allNet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  allNet:
